# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [3]:
!conda install numpy
!pip install numpy

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.11.0               |   py39hecd8cb5_0        14.4 MB
    ------------------------------------------------------------
                                           Total:        14.4 MB

The following packages will be UPDATED:

  conda                               4.10.3-py39hecd8cb5_0 --> 4.11.0-py39hecd8cb5_0


Proceed ([y]/n)? ^C

CondaSystemExit: 
Operation aborted.  Exiting.



In [ ]:
# install specicifc version of numpy
#!pip install numpy==1.23.0

In [ ]:
#!pip install numpy --upgrade

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [5]:
import numpy as np

In [6]:
np.__version__

'1.21.5'

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
type(my_list)

list

In [7]:
a=np.array(my_list)
a

array([1, 2, 3])

In [149]:
a=np.array([2,34,1,93,45])
a

array([ 2, 34,  1, 93, 45])

In [150]:
type(a)

numpy.ndarray

In [13]:
a.ndim

1

In [9]:
#array
a=np.array([2,3,4,5,6,3])
a

array([2, 3, 4, 5, 6, 3])

In [10]:
a.shape

(6,)

In [10]:
a.ndim

1

In [12]:
a.size

6

In [13]:
a.dtype

dtype('int64')

In [11]:
type(a)

numpy.ndarray

In [15]:

a = np.array([2,3,4,5])
b = np.array([2,3,4,5])

c = a + b

print(c)

[ 4  6  8 10]


In [12]:
b=np.array(my_list)
type(b)


numpy.ndarray

In [13]:
a=np.array(45)
a.ndim


0

In [14]:
a

array(45)

In [16]:
#matrix
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr.shape

(2, 3)

In [18]:
arr.ndim

2

In [24]:
my_matrix = [
             [1,2,3,14],
             [4,5,6,12],
             [7,8,9,34],
             [7,8,9,34]
                
            ]
print(my_matrix)


[[1, 2, 3, 14], [4, 5, 6, 12], [7, 8, 9, 34], [7, 8, 9, 34]]
<class 'list'>


In [26]:
b=np.array(my_matrix)
b.shape

(4, 4)

In [21]:
b.size

16

In [22]:
b.ndim

2

In [23]:
b.dtype

dtype('int64')

In [28]:
# new_a=
b=np.array([[1,2,3,4],[4,5,6,7],[3,7,8,9]])

In [29]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 7, 8, 9]])

In [76]:
b.shape

(3, 3)

In [32]:
#Tensor
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
b.ndim

3

In [34]:
b.size

12

In [35]:
b.shape

(2, 2, 3)

In [39]:
#Comparision of python list and numpy array performance
#python list

import time
start_time=time.time()

x=[i for i in range(1000000)]
y=[i for i in range(1000000)]

result=[]
for i in range(len(x)):
    result.append(x[i]+y[i])
    
end_time=time.time()
print(end_time-start_time)

0.18684887886047363


In [40]:
#numpy
start_time=time.time()

x=np.arange(1000000)
y=np.arange(1000000)

z=x+y
end_time=time.time()
print(end_time-start_time)

0.013226985931396484


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [33]:
np.arange(4,32)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [34]:
np.arange(4,32,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [35]:
new=np.arange(-5,-1)
new

array([-5, -4, -3, -2])

In [53]:
new=np.arange(40,0,-1)
new

array([40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
       23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1])

In [36]:
#(start,end(exclusive),jump)-syntax
a=np.arange(2,32,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [46]:
a= np.arange(1.20,70.10,3.2)
a

array([ 1.2,  4.4,  7.6, 10.8, 14. , 17.2, 20.4, 23.6, 26.8, 30. , 33.2,
       36.4, 39.6, 42.8, 46. , 49.2, 52.4, 55.6, 58.8, 62. , 65.2, 68.4])

In [38]:
a.dtype

dtype('float64')

### zeros and ones

Generate arrays/matrix of zeros or ones

In [39]:
a=np.zeros(7)
a

array([0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((4,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [33]:
np.ones(27)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### linspace
Return evenly spaced numbers over a specified interval.

In [53]:
np.linspace(23,90,35)

array([23.        , 24.97058824, 26.94117647, 28.91176471, 30.88235294,
       32.85294118, 34.82352941, 36.79411765, 38.76470588, 40.73529412,
       42.70588235, 44.67647059, 46.64705882, 48.61764706, 50.58823529,
       52.55882353, 54.52941176, 56.5       , 58.47058824, 60.44117647,
       62.41176471, 64.38235294, 66.35294118, 68.32352941, 70.29411765,
       72.26470588, 74.23529412, 76.20588235, 78.17647059, 80.14705882,
       82.11764706, 84.08823529, 86.05882353, 88.02941176, 90.        ])

In [59]:
a=np.linspace(32,41,22)

a

array([32.        , 32.42857143, 32.85714286, 33.28571429, 33.71428571,
       34.14285714, 34.57142857, 35.        , 35.42857143, 35.85714286,
       36.28571429, 36.71428571, 37.14285714, 37.57142857, 38.        ,
       38.42857143, 38.85714286, 39.28571429, 39.71428571, 40.14285714,
       40.57142857, 41.        ])

In [55]:
a=np.linspace(245,1000)
a


array([ 245.        ,  260.40816327,  275.81632653,  291.2244898 ,
        306.63265306,  322.04081633,  337.44897959,  352.85714286,
        368.26530612,  383.67346939,  399.08163265,  414.48979592,
        429.89795918,  445.30612245,  460.71428571,  476.12244898,
        491.53061224,  506.93877551,  522.34693878,  537.75510204,
        553.16326531,  568.57142857,  583.97959184,  599.3877551 ,
        614.79591837,  630.20408163,  645.6122449 ,  661.02040816,
        676.42857143,  691.83673469,  707.24489796,  722.65306122,
        738.06122449,  753.46938776,  768.87755102,  784.28571429,
        799.69387755,  815.10204082,  830.51020408,  845.91836735,
        861.32653061,  876.73469388,  892.14285714,  907.55102041,
        922.95918367,  938.36734694,  953.7755102 ,  969.18367347,
        984.59183673, 1000.        ])

In [59]:
a=np.linspace(1,10,100)
a

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [56]:
a=np.linspace(55,250,11)
a

array([ 55. ,  74.5,  94. , 113.5, 133. , 152.5, 172. , 191.5, 211. ,
       230.5, 250. ])

## eye

Creates an identity matrix

In [62]:
a=np.eye(9,dtype=int)
a

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [2]:
import numpy as np

In [72]:
np.random.rand(11)
              

array([0.0029982 , 0.30832744, 0.01178518, 0.70225922, 0.41911455,
       0.58797208, 0.99319116, 0.06417614, 0.91786671, 0.69818746,
       0.03898802])

In [75]:
np.random.rand(5,3)

array([[0.81112674, 0.1505074 , 0.23658419],
       [0.63426093, 0.56000179, 0.80477777],
       [0.54804369, 0.10710287, 0.85193121],
       [0.15930779, 0.92829645, 0.09992492],
       [0.64891897, 0.96670692, 0.51423547]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [8]:
np.random.randn(5)

array([-1.44069164,  0.35201315, -0.24617688, -0.84161958, -1.60416288])

In [87]:
a=np.random.randn(5,5)
a


array([[ 0.77827765, -0.39385425,  0.06891704, -0.49505682,  1.06621652],
       [ 0.70114684,  0.7504204 ,  0.42410306,  0.56000291,  0.67404381],
       [-0.27116624, -0.61464609, -0.34375755,  2.13549019, -0.88220602],
       [-1.24793698, -0.02145498,  0.61852588,  0.14085133,  0.41991261],
       [-2.14102991, -0.2662604 , -0.59037713,  0.17198702, -0.95836868]])

In [71]:
a=np.random.randn(2,3,2)
a


array([[[ 1.3450706 ,  0.25518178],
        [-0.62477994, -1.42283021],
        [-0.8277847 , -1.16947809]],

       [[-0.03519927,  0.29802433],
        [-0.13391214, -0.89616775],
        [ 0.56417269, -1.36737097]]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [81]:
np.random.randint(35)

31

In [82]:
np.random.randint(15,250,10)

array([159,  46,  66,  34,  81,  34, 185,  32, 124, 224])

In [93]:
a=np.random.randint(21,100,10)
a

array([54, 37, 24, 40, 25, 45, 35, 61, 29, 88])

In [84]:
a=np.random.randint(10,200,size=(2,2,10))
a

array([[[ 46,  73, 112,  14, 196, 130,  75,  61, 171,  60],
        [ 72,  88,  73,  68,  35,  32, 113,  69,  92, 113]],

       [[ 37, 149, 185,  63,  10,  60, 163,  55,  15,  36],
        [158, 161,  84, 189,  64, 163, 196, 120, 181, 136]]])

## random float number

In [103]:
np.random.uniform(34.22,145.10)

41.56833779003767

In [1]:
np.random.uniform(34.22,145.10,15)

NameError: name 'np' is not defined

In [99]:
#generate number between 50 to 100
temp_list=[]
for i in range(0,10):
    result=round(np.random.uniform(50.10,165.45),4)
    temp_list.append(result)

print(temp_list)

[93.6557, 99.7974, 59.7798, 153.8352, 138.3484, 149.0163, 131.239, 89.7097, 129.7375, 131.204]


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [13]:
arr = np.arange(0.00,1.00,.01).reshape(10,10)
arr

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [107]:
arr.ndim

1

In [108]:
arr.shape

(25,)

## Reshape
Returns an array containing the same data with a new shape.

In [139]:
arr=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24,25,26,27,28,29])

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [126]:
arr.ndim

1

In [127]:
arr.shape

(30,)

In [140]:
arr=arr.reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [129]:
arr.shape

(6, 5)

In [130]:
arr.ndim

2

In [ ]:
import numpy as np
arr33=np.random.randint(1,500,size=500)
arr33

In [164]:
arr33.shape

(500,)

In [165]:
arr33.ndim

1

In [171]:
arr34=arr33.reshape(50,10)
arr34.shape

(50, 10)

In [172]:
arr34.shape

(50, 10)

In [173]:
arr34.ndim

2

In [180]:
arr2=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
arr2=arr2.reshape(2,3,2)
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [182]:
arr2.shape

(2, 3, 2)

In [179]:
arr2.ndim

3

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [131]:
a= np.array([ 55. ,  74.5,  94. ,342, 113.5, 133. , 152.5,12, 172. , 191.5, 211. ,
       230.5, 250. ])
a

array([ 55. ,  74.5,  94. , 342. , 113.5, 133. , 152.5,  12. , 172. ,
       191.5, 211. , 230.5, 250. ])

In [185]:
a.max()

342.0

In [186]:
a.argmax()

3

In [187]:
a.min()

12.0

In [188]:
a.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [141]:
# Vector
arr.shape

(6, 5)

In [142]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [144]:
# Notice the two sets of brackets
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [146]:
arr.reshape(1,30).shape

(1, 30)

In [147]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [66]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [148]:
arr.dtype

dtype('int64')

In [ ]:
#The end.