In [6]:
import numpy as np
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#indexing
a[2]

2

In [16]:
#slicing
a[3:9]
a[::2]
a[-1:-6:-1]

array([10,  9,  8,  7,  6])

In [18]:
# Broadcasting
a[3]=600
a[0:2]=500
a

array([500, 500,   2, 600,   4,   5,   6,   7,   8,   9,  10])

In [33]:
r=np.array([[10,20,30,40,50],[50,60,20,40,60],[2,6,4,3,1]])
r

array([[10, 20, 30, 40, 50],
       [50, 60, 20, 40, 60],
       [ 2,  6,  4,  3,  1]])

In [35]:
r[0:1,2:]
r[1:,0:2]

array([[50, 60],
       [ 2,  6]])

In [54]:
# Selection
a=np.arange(0,11)
a=[a>2]
a

[array([False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True])]

In [74]:
a=np.arange(0,11)
b = a>4
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [75]:
a[a > 2]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a[(a>4) & (a<9)]

array([5, 6, 7, 8])

In [82]:
t=np.arange(45).reshape(3,3,5)
t

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [87]:
t[0][1]>6

array([False, False,  True,  True,  True])

In [102]:
# Operations
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [95]:
np.add(a,a)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [97]:
np.subtract(a,a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
np.multiply(a,a)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [104]:
np.divide(a,a)

C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\111323567.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(a,a)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
np.concatenate((a,a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [101]:
1/a

C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [107]:
a/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0
C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\4102073204.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [109]:
# universal function
print(a)
np.sqrt(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [110]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [111]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [112]:
np.log(a)

C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [113]:
np.log2(a)

C:\Users\DELL\AppData\Local\Temp\ipykernel_21828\2088242240.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(a)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ,
       3.32192809])

In [114]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)


[6 6]
