In [2]:
import numpy as np
np.sqrt(10)

3.1622776601683795

In [2]:
import numpy as np
a=np.array([10,20,30,20,10,25,26,30])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)


8
(8,)
1
int32


In [20]:
np.random.rand(2,3,2)

array([[[0.09401191, 0.99433177],
        [0.176222  , 0.71268222],
        [0.99622972, 0.48482081]],

       [[0.08566431, 0.25187308],
        [0.69147473, 0.31511571],
        [0.01333594, 0.99558593]]])

In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
print(arr[::5])

[1 6]


In [26]:
np.random.randint(2,6)

5

In [27]:
np.random.randn(3,2,3)

array([[[-1.53893688,  0.87382647, -0.23023872],
        [ 0.95847397,  1.08578021, -1.71306129]],

       [[-0.33096962, -0.31302512, -1.20587619],
        [-1.5696044 ,  0.25736206, -0.44263122]],

       [[ 0.21140674, -0.2980387 , -0.72247034],
        [-2.21706715, -1.88441988, -1.26808117]]])

In [28]:
np.random.ranf(10)

array([0.18274436, 0.63235746, 0.68293427, 0.39446425, 0.44716239,
       0.35378899, 0.60411471, 0.94770989, 0.93318685, 0.86123363])

In [7]:
np.zeros((2,5,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [8]:
np.ones((2,5,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [21]:
arr=np.array([10,20,30,40,50,50,60,70,80,90])
b=arr.reshape(2,5)
b.shape
b.size
b.dtype


dtype('int32')

In [30]:
a=np.arange(1,51,1)
a.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [1]:
np.linspace(10,50,5)

NameError: name 'np' is not defined

In [34]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.random.rand(5,5)

array([[0.56133561, 0.20582212, 0.70581086, 0.41191134, 0.17091746],
       [0.56577261, 0.12691522, 0.58925685, 0.54333381, 0.50422487],
       [0.06738864, 0.92870355, 0.19950853, 0.783257  , 0.52614621],
       [0.89132359, 0.75560099, 0.662666  , 0.90732096, 0.52152081],
       [0.1764877 , 0.12308399, 0.78944146, 0.9632196 , 0.86628992]])

In [39]:
np.random.randn(5,5)

array([[-0.37055757,  0.87341853, -1.55779729, -0.71512439,  1.22292927],
       [-0.05616935,  0.43587035, -0.0494624 ,  0.8521525 , -0.22923334],
       [-0.68238477,  1.05379157,  0.81582001, -0.66311224, -1.59507723],
       [-0.43002448, -0.57303842, -0.23703979, -0.75486118,  0.70029039],
       [-0.80603242, -0.44822272,  0.23211053, -0.33302066,  0.52871389]])

In [42]:
np.random.randint(5,50)

array([[25, 43,  8],
       [18, 46, 49]])

In [43]:
np.random.randint(5,50,size=(2,3))

array([[23, 41, 35],
       [16, 41, 29]])

In [51]:
np.random.uniform(10,20,10)
print(n)
print(n.max())


[17.49417541 13.3408038  12.1276987  19.08048602 16.46298032 10.11809196
 10.59466382 12.21179499 14.47359399 13.87569453]
19.080486021053055


In [59]:
n=np.random.randint(10,50,10)
print(n)
print(n.max())
print(n.argmax())
print(n.min())
print(n.argmin())

[30 42 29 26 16 23 30 25 12 16]
42
1
12
8
